movieproject/movieapp/urls.py
from django.urls import path
from . import views
app_name='movieapp'
urlpatterns = [
    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add_movie, name='add_movie'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete'),






]

movieproject/movieproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("movieapp.urls"))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

movieproject/movieapp/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc','year','img']

movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Movie
from .forms import MovieForm

# Create your views here.
def index(request):
    movie=Movie.objects.all()
    context={
        'movie_list':movie
    }
    return render(request,'index.html',context)
def detail(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render(request,"detail.html",{'movie':movie})


def add_movie(request):
    if request.method=="POST":
        name=request.POST.get('name',)
        desc = request.POST.get('desc', )
        year = request.POST.get('year', )
        img = request.FILES['img']
        movie=Movie(name=name,desc=desc,year=year,img=img)
        movie.save()
    return render(request,'add.html')


def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None, request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})
def delete(request,id):
    if request.method=='POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
    <input type="text" name="name" placeholder="enter your movie name">
    <input type="text" name="desc" placeholder="enter your movie descripition">
    <input type="text" name="year" placeholder="enter your movie year">
    <input type="file" name="img">
    <input type="submit">

</form>
{% endblock %}

movieproject/templates/base.html
<!DOCTYPE html>
    {% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>


<!-- Image and text -->

<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">

    Online Movie Store
         {% for i in movie_list %}
     <a href="{% url 'movieapp:detail' i.id %}">add  </a>

  </a>

</nav>
{% endfor %}

{% block body %}

{% endblock %}

</body>
</html>

movieproject/templates/delete.html
<form method="POST">
  {% csrf_token %}
  are u want to delete this movie?
  <input type="submit">
</form>

movieproject/templates/detail.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{movie.img.url}}" width="300" height="300">
    </div>
    <div class="col-md-6">
        <h6>{{movie.name}}</h6>
        <h6>{{movie.desc}}</h6>
       <h6>{{movie.year}}</h6>
        <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">update</a>
        <a class="btn btn-dangour" href="{% url 'movieapp:delete' movie.id %}">delete</a>


    </div>
      </div>
        </div>


{% endblock %}

movieproject/templates/edit.html
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit">
</form>

movieproject/templates/index.html
{% extends 'base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        {% for i in movie_list %}

        <div class="col-md-3">
        <div class="card">
           <img src="{{i.img.url}}" class="card-img-top" alt="" height="250">
           <div class="card-body">
              <h5 class="card-title">{{i.name}}</h5>
              <p class="card-text">{{i.price}}</p>
               <a href="{% url 'movieapp:detail' i.id %}"  class="btn btn-primary">Go Where </a>



    </div>
  </div>
        </div>
     {% endfor %}
    </div>
</div>





{% endblock %}